### ISSUE TITLE
Any plans to support creating music xml files?

### ISSUE THREAD

**Issue by reznet** [vdaron/MusicXml.Net#4]
I'm looking to add music xml output to my project, https://github.com/reznet/S3MParser, which is written in C#.  I'd rather not write my own music xml library if one exists, but it seems that MusicXml.Net is only for reading scores.  Are there any plans to extend it to support writing scores as well?

**Comment by vdaron** [comment]
Hi,

Unfortunately, I do not have the time right now to add write support to MusicXMl.Net.

Nevertheless, MusicXML.Net can be a good start if you want a library to create musicxml files, You probably do not need the complete scope of the musicxml standard immediately.

Regards,

Vincent.
