### ISSUE TITLE
Width of measure should be double

### ISSUE THREAD

**Issue by LimmaPaulus** [vdaron/MusicXml.Net#5]
Hi!

I'm using your nice library to parse MusicXml file created by MuseScore. MuseScore seems to write measure widths with doubles, which causes exception when trying to parse with MusicXml.net.

**Comment by vdaron** [comment]
Hi,

Back from vacations.

Could you create a bug report with an Xml file to be able to reproduce the problem ?

Thanks

Vincent.

**Comment by sambaker** [comment]
I had the same errors - to fix it, I changed line 63 of MusicXmlParser.cs from:

	measure.Width = Convert.ToInt32(measureWidthAttribute.InnerText);

to
	measure.Width = (int)Convert.ToDouble(measureWidthAttribute.InnerText);

which fixes the parsing but obviously will lose precision. However in my case I didn't need measure.Width, I just needed to fix the exceptions. Attached is an XML file that causes an exception without my change.

[Feel_Like_Funkin_It_Up.txt](https://github.com/vdaron/MusicXml.Net/files/151686/Feel_Like_Funkin_It_Up.txt)
