### ISSUE TITLE
Accidental property is not appearing

### ISSUE THREAD

**Issue by giorgosde** [vdaron/MusicXml.Net#9]
Hello,

congrats for this nice library.

Issue is all about "Accidental" property that is not appearing when using the library via Nuget Packages. It does appear when using the code directly. 

[Sample](http://giorgosdel.esy.es/musicxml_noAccidental.png)

Thank you.

**Comment by vdaron** [comment]
You are probably not using the last version. Try to update your nuget packages

**Comment by giorgosde** [comment]
I am using version 2.0.1 which - as far as I can see - is the most resent release and problem still exists.

But again, it works when I use the code directly (not through Nugets).

Thank you.

**Comment by vdaron** [comment]
Net Nuget package published with code migrate to netstandard 2.1. should be fixed I guess..
